CREATE TABLE drivers (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    phone VARCHAR(20) NOT NULL UNIQUE,
    car_id BIGINT UNIQUE,
    available BOOLEAN DEFAULT TRUE,
    FOREIGN KEY (car_id) REFERENCES cars(id)
) engine=InnoDB;